module syn_fifo (empty,
    full,
    overflow,
    underflow,
    clk,
    rd_en,
    rst,
    wr_en,
    data_in,
    data_out,
    VDD,
    VGND);
 output empty;
 output full;
 output overflow;
 output underflow;
 input clk;
 input rd_en;
 input rst;
 input wr_en;
 input [7:0] data_in;
 output [7:0] data_out;
 inout VDD;
 inout VGND;

 wire _073_;
 wire _074_;
 wire _075_;
 wire _076_;
 wire _077_;
 wire _078_;
 wire _079_;
 wire _080_;
 wire _081_;
 wire _082_;
 wire _083_;
 wire _084_;
 wire _085_;
 wire _086_;
 wire _087_;
 wire _088_;
 wire _089_;
 wire _090_;
 wire _091_;
 wire _092_;
 wire _093_;
 wire _094_;
 wire _095_;
 wire _096_;
 wire _097_;
 wire _098_;
 wire _099_;
 wire _164_;
 wire _165_;
 wire _166_;
 wire _167_;
 wire _168_;
 wire _169_;
 wire _170_;
 wire _171_;
 wire _172_;
 wire _173_;
 wire _174_;
 wire _175_;
 wire _176_;
 wire _177_;
 wire _178_;
 wire _179_;
 wire _180_;
 wire _181_;
 wire _182_;
 wire _183_;
 wire _184_;
 wire _185_;
 wire _186_;
 wire _187_;
 wire _188_;
 wire _189_;
 wire _190_;
 wire _191_;
 wire _192_;
 wire _193_;
 wire _194_;
 wire _195_;
 wire _196_;
 wire _197_;
 wire _198_;
 wire _199_;
 wire _200_;
 wire _201_;
 wire _202_;
 wire _203_;
 wire _204_;
 wire _205_;
 wire _212_;
 wire zero_;
 wire clknet_0_clk;
 wire clknet_3_0__leaf_clk;
 wire clknet_3_1__leaf_clk;
 wire clknet_3_2__leaf_clk;
 wire clknet_3_3__leaf_clk;
 wire clknet_3_4__leaf_clk;
 wire clknet_3_5__leaf_clk;
 wire clknet_3_6__leaf_clk;
 wire clknet_3_7__leaf_clk;
 wire [0:0] _218_;
 wire [0:0] _221_;
 wire [7:0] \mem[0] ;
 wire [7:0] \mem[1] ;
 wire [7:0] \mem[2] ;
 wire [7:0] \mem[3] ;
 wire [7:0] \mem[4] ;
 wire [7:0] \mem[5] ;
 wire [7:0] \mem[6] ;
 wire [7:0] \mem[7] ;
 wire [3:0] rd_ptr;
 wire [3:0] wr_ptr;

 sky130_fd_sc_hd__conb_1 TIE_ZERO_zero_ (.VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .LO(zero_));
 sky130_fd_sc_hd__clkinv_1 _231_ (.A(rd_en),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_164_));
 sky130_fd_sc_hd__clkinv_1 _232_ (.A(wr_en),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_165_));
 sky130_fd_sc_hd__mux4_2 _233_ (.A0(\mem[1] [6]),
    .A1(\mem[5] [6]),
    .A2(\mem[3] [6]),
    .A3(\mem[7] [6]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_166_));
 sky130_fd_sc_hd__mux4_2 _234_ (.A0(\mem[0] [6]),
    .A1(\mem[4] [6]),
    .A2(\mem[2] [6]),
    .A3(\mem[6] [6]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_167_));
 sky130_fd_sc_hd__mux2_1 _235_ (.A0(_167_),
    .A1(_166_),
    .S(rd_ptr[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_079_));
 sky130_fd_sc_hd__mux4_2 _236_ (.A0(\mem[1] [5]),
    .A1(\mem[5] [5]),
    .A2(\mem[3] [5]),
    .A3(\mem[7] [5]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_168_));
 sky130_fd_sc_hd__mux4_2 _237_ (.A0(\mem[0] [5]),
    .A1(\mem[4] [5]),
    .A2(\mem[2] [5]),
    .A3(\mem[6] [5]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_169_));
 sky130_fd_sc_hd__mux2_1 _238_ (.A0(_169_),
    .A1(_168_),
    .S(rd_ptr[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_078_));
 sky130_fd_sc_hd__mux4_2 _239_ (.A0(\mem[1] [4]),
    .A1(\mem[5] [4]),
    .A2(\mem[3] [4]),
    .A3(\mem[7] [4]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_170_));
 sky130_fd_sc_hd__mux4_2 _240_ (.A0(\mem[0] [4]),
    .A1(\mem[4] [4]),
    .A2(\mem[2] [4]),
    .A3(\mem[6] [4]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_171_));
 sky130_fd_sc_hd__mux2_1 _241_ (.A0(_171_),
    .A1(_170_),
    .S(rd_ptr[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_077_));
 sky130_fd_sc_hd__mux4_2 _242_ (.A0(\mem[1] [3]),
    .A1(\mem[5] [3]),
    .A2(\mem[3] [3]),
    .A3(\mem[7] [3]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_172_));
 sky130_fd_sc_hd__mux4_2 _243_ (.A0(\mem[0] [3]),
    .A1(\mem[4] [3]),
    .A2(\mem[2] [3]),
    .A3(\mem[6] [3]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_173_));
 sky130_fd_sc_hd__mux2_1 _244_ (.A0(_173_),
    .A1(_172_),
    .S(rd_ptr[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_076_));
 sky130_fd_sc_hd__mux4_2 _245_ (.A0(\mem[1] [2]),
    .A1(\mem[5] [2]),
    .A2(\mem[3] [2]),
    .A3(\mem[7] [2]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_174_));
 sky130_fd_sc_hd__mux4_2 _246_ (.A0(\mem[0] [2]),
    .A1(\mem[4] [2]),
    .A2(\mem[2] [2]),
    .A3(\mem[6] [2]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_175_));
 sky130_fd_sc_hd__mux2_1 _247_ (.A0(_175_),
    .A1(_174_),
    .S(rd_ptr[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_075_));
 sky130_fd_sc_hd__mux4_2 _248_ (.A0(\mem[1] [1]),
    .A1(\mem[5] [1]),
    .A2(\mem[3] [1]),
    .A3(\mem[7] [1]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_176_));
 sky130_fd_sc_hd__mux4_2 _249_ (.A0(\mem[0] [1]),
    .A1(\mem[4] [1]),
    .A2(\mem[2] [1]),
    .A3(\mem[6] [1]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_177_));
 sky130_fd_sc_hd__mux2_1 _250_ (.A0(_177_),
    .A1(_176_),
    .S(rd_ptr[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_074_));
 sky130_fd_sc_hd__mux4_2 _251_ (.A0(\mem[1] [0]),
    .A1(\mem[5] [0]),
    .A2(\mem[3] [0]),
    .A3(\mem[7] [0]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_178_));
 sky130_fd_sc_hd__mux4_2 _252_ (.A0(\mem[0] [0]),
    .A1(\mem[4] [0]),
    .A2(\mem[2] [0]),
    .A3(\mem[6] [0]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_179_));
 sky130_fd_sc_hd__mux2_1 _253_ (.A0(_179_),
    .A1(_178_),
    .S(rd_ptr[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_073_));
 sky130_fd_sc_hd__xnor2_1 _254_ (.A(rd_ptr[0]),
    .B(wr_ptr[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_180_));
 sky130_fd_sc_hd__xnor2_1 _255_ (.A(rd_ptr[2]),
    .B(wr_ptr[2]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_181_));
 sky130_fd_sc_hd__xnor2_1 _256_ (.A(rd_ptr[1]),
    .B(wr_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_182_));
 sky130_fd_sc_hd__nand3_1 _257_ (.A(_180_),
    .B(_181_),
    .C(_182_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_183_));
 sky130_fd_sc_hd__xor2_1 _258_ (.A(wr_ptr[3]),
    .B(rd_ptr[3]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_184_));
 sky130_fd_sc_hd__xnor2_1 _259_ (.A(wr_ptr[3]),
    .B(rd_ptr[3]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_185_));
 sky130_fd_sc_hd__nor2_1 _260_ (.A(_183_),
    .B(_184_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_098_));
 sky130_fd_sc_hd__a41oi_1 _261_ (.A1(_180_),
    .A2(_181_),
    .A3(_182_),
    .A4(_185_),
    .B1(_164_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_089_));
 sky130_fd_sc_hd__nand4_1 _262_ (.A(_180_),
    .B(_181_),
    .C(_182_),
    .D(_184_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_186_));
 sky130_fd_sc_hd__clkinv_1 _263_ (.A(_186_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_099_));
 sky130_fd_sc_hd__a41oi_1 _264_ (.A1(_180_),
    .A2(_181_),
    .A3(_182_),
    .A4(_184_),
    .B1(_165_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_187_));
 sky130_fd_sc_hd__nand2_1 _265_ (.A(wr_en),
    .B(_186_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_188_));
 sky130_fd_sc_hd__and2_0 _266_ (.A(wr_ptr[0]),
    .B(_187_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_189_));
 sky130_fd_sc_hd__nand2_1 _267_ (.A(wr_ptr[1]),
    .B(_189_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_190_));
 sky130_fd_sc_hd__nor2_1 _268_ (.A(wr_ptr[2]),
    .B(_190_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_084_));
 sky130_fd_sc_hd__nand2b_1 _269_ (.A_N(wr_ptr[1]),
    .B(wr_ptr[2]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_191_));
 sky130_fd_sc_hd__nor3_1 _270_ (.A(wr_ptr[0]),
    .B(_188_),
    .C(_191_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_085_));
 sky130_fd_sc_hd__nor4b_1 _271_ (.A(wr_ptr[0]),
    .B(_188_),
    .C(wr_ptr[2]),
    .D_N(wr_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_083_));
 sky130_fd_sc_hd__lpflow_isobufsrc_1 _272_ (.A(_189_),
    .SLEEP(_191_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_086_));
 sky130_fd_sc_hd__nor3b_1 _273_ (.A(wr_ptr[2]),
    .B(wr_ptr[1]),
    .C_N(_189_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_082_));
 sky130_fd_sc_hd__nor4_1 _274_ (.A(wr_ptr[0]),
    .B(wr_ptr[2]),
    .C(wr_ptr[1]),
    .D(_188_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_081_));
 sky130_fd_sc_hd__mux4_2 _275_ (.A0(\mem[1] [7]),
    .A1(\mem[5] [7]),
    .A2(\mem[3] [7]),
    .A3(\mem[7] [7]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_192_));
 sky130_fd_sc_hd__mux4_2 _276_ (.A0(\mem[0] [7]),
    .A1(\mem[4] [7]),
    .A2(\mem[2] [7]),
    .A3(\mem[6] [7]),
    .S0(rd_ptr[2]),
    .S1(rd_ptr[1]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_193_));
 sky130_fd_sc_hd__mux2_1 _277_ (.A0(_193_),
    .A1(_192_),
    .S(rd_ptr[0]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_080_));
 sky130_fd_sc_hd__and4b_1 _278_ (.A_N(wr_ptr[0]),
    .B(wr_ptr[2]),
    .C(wr_ptr[1]),
    .D(_187_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_087_));
 sky130_fd_sc_hd__and4_1 _279_ (.A(wr_ptr[0]),
    .B(wr_ptr[2]),
    .C(wr_ptr[1]),
    .D(_187_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_088_));
 sky130_fd_sc_hd__nor2_1 _280_ (.A(_165_),
    .B(_186_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_205_));
 sky130_fd_sc_hd__nor3_1 _281_ (.A(_164_),
    .B(_183_),
    .C(_184_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_212_));
 sky130_fd_sc_hd__and2_0 _282_ (.A(rd_ptr[0]),
    .B(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_194_));
 sky130_fd_sc_hd__nor2_1 _283_ (.A(rd_ptr[0]),
    .B(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_195_));
 sky130_fd_sc_hd__nor3_1 _284_ (.A(rst),
    .B(_194_),
    .C(_195_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_090_));
 sky130_fd_sc_hd__a21oi_1 _285_ (.A1(wr_ptr[1]),
    .A2(_189_),
    .B1(wr_ptr[2]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_196_));
 sky130_fd_sc_hd__nor3_1 _286_ (.A(rst),
    .B(_088_),
    .C(_196_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_091_));
 sky130_fd_sc_hd__a21oi_1 _287_ (.A1(wr_ptr[1]),
    .A2(_189_),
    .B1(rst),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_197_));
 sky130_fd_sc_hd__o21a_1 _288_ (.A1(wr_ptr[1]),
    .A2(_189_),
    .B1(_197_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_092_));
 sky130_fd_sc_hd__nor2_1 _289_ (.A(wr_ptr[0]),
    .B(_187_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_198_));
 sky130_fd_sc_hd__nor3_1 _290_ (.A(rst),
    .B(_189_),
    .C(_198_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_093_));
 sky130_fd_sc_hd__and3_1 _291_ (.A(rd_ptr[2]),
    .B(rd_ptr[1]),
    .C(_194_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_199_));
 sky130_fd_sc_hd__nand4_1 _292_ (.A(rd_ptr[2]),
    .B(rd_ptr[0]),
    .C(rd_ptr[1]),
    .D(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_200_));
 sky130_fd_sc_hd__a21oi_1 _293_ (.A1(rd_ptr[1]),
    .A2(_194_),
    .B1(rd_ptr[2]),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_201_));
 sky130_fd_sc_hd__nor3_1 _294_ (.A(rst),
    .B(_199_),
    .C(_201_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_094_));
 sky130_fd_sc_hd__a21oi_1 _295_ (.A1(rd_ptr[1]),
    .A2(_194_),
    .B1(rst),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_202_));
 sky130_fd_sc_hd__o21a_1 _296_ (.A1(rd_ptr[1]),
    .A2(_194_),
    .B1(_202_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_095_));
 sky130_fd_sc_hd__xor2_1 _297_ (.A(rd_ptr[3]),
    .B(_200_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(_203_));
 sky130_fd_sc_hd__nor2_1 _298_ (.A(rst),
    .B(_203_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_096_));
 sky130_fd_sc_hd__xnor2_1 _299_ (.A(wr_ptr[3]),
    .B(_088_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_204_));
 sky130_fd_sc_hd__nor2_1 _300_ (.A(rst),
    .B(_204_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Y(_097_));
 sky130_fd_sc_hd__edfxtp_1 _301_ (.CLK(clknet_3_7__leaf_clk),
    .D(data_in[0]),
    .DE(_088_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[7] [0]));
 sky130_fd_sc_hd__edfxtp_1 _302_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[1]),
    .DE(_088_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[7] [1]));
 sky130_fd_sc_hd__edfxtp_1 _303_ (.CLK(clknet_3_6__leaf_clk),
    .D(data_in[2]),
    .DE(_088_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[7] [2]));
 sky130_fd_sc_hd__edfxtp_1 _304_ (.CLK(clknet_3_4__leaf_clk),
    .D(data_in[3]),
    .DE(_088_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[7] [3]));
 sky130_fd_sc_hd__edfxtp_1 _305_ (.CLK(clknet_3_2__leaf_clk),
    .D(data_in[4]),
    .DE(_088_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[7] [4]));
 sky130_fd_sc_hd__edfxtp_1 _306_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[5]),
    .DE(_088_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[7] [5]));
 sky130_fd_sc_hd__edfxtp_1 _307_ (.CLK(clknet_3_5__leaf_clk),
    .D(data_in[6]),
    .DE(_088_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[7] [6]));
 sky130_fd_sc_hd__edfxtp_1 _308_ (.CLK(clknet_3_2__leaf_clk),
    .D(data_in[7]),
    .DE(_088_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[7] [7]));
 sky130_fd_sc_hd__edfxtp_1 _309_ (.CLK(clknet_3_7__leaf_clk),
    .D(data_in[0]),
    .DE(_087_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[6] [0]));
 sky130_fd_sc_hd__edfxtp_1 _310_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[1]),
    .DE(_087_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[6] [1]));
 sky130_fd_sc_hd__edfxtp_1 _311_ (.CLK(clknet_3_6__leaf_clk),
    .D(data_in[2]),
    .DE(_087_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[6] [2]));
 sky130_fd_sc_hd__edfxtp_1 _312_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[3]),
    .DE(_087_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[6] [3]));
 sky130_fd_sc_hd__edfxtp_1 _313_ (.CLK(clknet_3_2__leaf_clk),
    .D(data_in[4]),
    .DE(_087_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[6] [4]));
 sky130_fd_sc_hd__edfxtp_1 _314_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[5]),
    .DE(_087_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[6] [5]));
 sky130_fd_sc_hd__edfxtp_1 _315_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[6]),
    .DE(_087_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[6] [6]));
 sky130_fd_sc_hd__edfxtp_1 _316_ (.CLK(clknet_3_3__leaf_clk),
    .D(data_in[7]),
    .DE(_087_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[6] [7]));
 sky130_fd_sc_hd__edfxtp_1 _317_ (.CLK(clknet_3_7__leaf_clk),
    .D(data_in[0]),
    .DE(_086_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[5] [0]));
 sky130_fd_sc_hd__edfxtp_1 _318_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[1]),
    .DE(_086_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[5] [1]));
 sky130_fd_sc_hd__edfxtp_1 _319_ (.CLK(clknet_3_6__leaf_clk),
    .D(data_in[2]),
    .DE(_086_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[5] [2]));
 sky130_fd_sc_hd__edfxtp_1 _320_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[3]),
    .DE(_086_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[5] [3]));
 sky130_fd_sc_hd__edfxtp_1 _321_ (.CLK(clknet_3_2__leaf_clk),
    .D(data_in[4]),
    .DE(_086_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[5] [4]));
 sky130_fd_sc_hd__edfxtp_1 _322_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[5]),
    .DE(_086_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[5] [5]));
 sky130_fd_sc_hd__edfxtp_1 _323_ (.CLK(clknet_3_4__leaf_clk),
    .D(data_in[6]),
    .DE(_086_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[5] [6]));
 sky130_fd_sc_hd__edfxtp_1 _324_ (.CLK(clknet_3_2__leaf_clk),
    .D(data_in[7]),
    .DE(_086_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[5] [7]));
 sky130_fd_sc_hd__edfxtp_1 _325_ (.CLK(clknet_3_7__leaf_clk),
    .D(data_in[0]),
    .DE(_085_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[4] [0]));
 sky130_fd_sc_hd__edfxtp_1 _326_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[1]),
    .DE(_085_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[4] [1]));
 sky130_fd_sc_hd__edfxtp_1 _327_ (.CLK(clknet_3_6__leaf_clk),
    .D(data_in[2]),
    .DE(_085_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[4] [2]));
 sky130_fd_sc_hd__edfxtp_1 _328_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[3]),
    .DE(_085_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[4] [3]));
 sky130_fd_sc_hd__edfxtp_1 _329_ (.CLK(clknet_3_3__leaf_clk),
    .D(data_in[4]),
    .DE(_085_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[4] [4]));
 sky130_fd_sc_hd__edfxtp_1 _330_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[5]),
    .DE(_085_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[4] [5]));
 sky130_fd_sc_hd__edfxtp_1 _331_ (.CLK(clknet_3_4__leaf_clk),
    .D(data_in[6]),
    .DE(_085_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[4] [6]));
 sky130_fd_sc_hd__edfxtp_1 _332_ (.CLK(clknet_3_3__leaf_clk),
    .D(data_in[7]),
    .DE(_085_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[4] [7]));
 sky130_fd_sc_hd__edfxtp_1 _333_ (.CLK(clknet_3_7__leaf_clk),
    .D(data_in[0]),
    .DE(_084_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[3] [0]));
 sky130_fd_sc_hd__edfxtp_1 _334_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[1]),
    .DE(_084_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[3] [1]));
 sky130_fd_sc_hd__edfxtp_1 _335_ (.CLK(clknet_3_6__leaf_clk),
    .D(data_in[2]),
    .DE(_084_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[3] [2]));
 sky130_fd_sc_hd__edfxtp_1 _336_ (.CLK(clknet_3_4__leaf_clk),
    .D(data_in[3]),
    .DE(_084_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[3] [3]));
 sky130_fd_sc_hd__edfxtp_1 _337_ (.CLK(clknet_3_2__leaf_clk),
    .D(data_in[4]),
    .DE(_084_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[3] [4]));
 sky130_fd_sc_hd__edfxtp_1 _338_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[5]),
    .DE(_084_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[3] [5]));
 sky130_fd_sc_hd__edfxtp_1 _339_ (.CLK(clknet_3_5__leaf_clk),
    .D(data_in[6]),
    .DE(_084_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[3] [6]));
 sky130_fd_sc_hd__edfxtp_1 _340_ (.CLK(clknet_3_2__leaf_clk),
    .D(data_in[7]),
    .DE(_084_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[3] [7]));
 sky130_fd_sc_hd__edfxtp_1 _341_ (.CLK(clknet_3_7__leaf_clk),
    .D(data_in[0]),
    .DE(_083_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[2] [0]));
 sky130_fd_sc_hd__edfxtp_1 _342_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[1]),
    .DE(_083_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[2] [1]));
 sky130_fd_sc_hd__edfxtp_1 _343_ (.CLK(clknet_3_6__leaf_clk),
    .D(data_in[2]),
    .DE(_083_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[2] [2]));
 sky130_fd_sc_hd__edfxtp_1 _344_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[3]),
    .DE(_083_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[2] [3]));
 sky130_fd_sc_hd__edfxtp_1 _345_ (.CLK(clknet_3_3__leaf_clk),
    .D(data_in[4]),
    .DE(_083_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[2] [4]));
 sky130_fd_sc_hd__edfxtp_1 _346_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[5]),
    .DE(_083_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[2] [5]));
 sky130_fd_sc_hd__edfxtp_1 _347_ (.CLK(clknet_3_4__leaf_clk),
    .D(data_in[6]),
    .DE(_083_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[2] [6]));
 sky130_fd_sc_hd__edfxtp_1 _348_ (.CLK(clknet_3_3__leaf_clk),
    .D(data_in[7]),
    .DE(_083_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[2] [7]));
 sky130_fd_sc_hd__edfxtp_1 _349_ (.CLK(clknet_3_7__leaf_clk),
    .D(data_in[0]),
    .DE(_082_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[1] [0]));
 sky130_fd_sc_hd__edfxtp_1 _350_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[1]),
    .DE(_082_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[1] [1]));
 sky130_fd_sc_hd__edfxtp_1 _351_ (.CLK(clknet_3_6__leaf_clk),
    .D(data_in[2]),
    .DE(_082_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[1] [2]));
 sky130_fd_sc_hd__edfxtp_1 _352_ (.CLK(clknet_3_4__leaf_clk),
    .D(data_in[3]),
    .DE(_082_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[1] [3]));
 sky130_fd_sc_hd__edfxtp_1 _353_ (.CLK(clknet_3_2__leaf_clk),
    .D(data_in[4]),
    .DE(_082_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[1] [4]));
 sky130_fd_sc_hd__edfxtp_1 _354_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[5]),
    .DE(_082_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[1] [5]));
 sky130_fd_sc_hd__edfxtp_1 _355_ (.CLK(clknet_3_4__leaf_clk),
    .D(data_in[6]),
    .DE(_082_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[1] [6]));
 sky130_fd_sc_hd__edfxtp_1 _356_ (.CLK(clknet_3_2__leaf_clk),
    .D(data_in[7]),
    .DE(_082_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[1] [7]));
 sky130_fd_sc_hd__edfxtp_1 _357_ (.CLK(clknet_3_7__leaf_clk),
    .D(data_in[0]),
    .DE(_081_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[0] [0]));
 sky130_fd_sc_hd__edfxtp_1 _358_ (.CLK(clknet_3_0__leaf_clk),
    .D(data_in[1]),
    .DE(_081_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[0] [1]));
 sky130_fd_sc_hd__edfxtp_1 _359_ (.CLK(clknet_3_6__leaf_clk),
    .D(data_in[2]),
    .DE(_081_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[0] [2]));
 sky130_fd_sc_hd__edfxtp_1 _360_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[3]),
    .DE(_081_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[0] [3]));
 sky130_fd_sc_hd__edfxtp_1 _361_ (.CLK(clknet_3_3__leaf_clk),
    .D(data_in[4]),
    .DE(_081_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[0] [4]));
 sky130_fd_sc_hd__edfxtp_1 _362_ (.CLK(clknet_3_1__leaf_clk),
    .D(data_in[5]),
    .DE(_081_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[0] [5]));
 sky130_fd_sc_hd__edfxtp_1 _363_ (.CLK(clknet_3_3__leaf_clk),
    .D(data_in[6]),
    .DE(_081_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[0] [6]));
 sky130_fd_sc_hd__edfxtp_1 _364_ (.CLK(clknet_3_3__leaf_clk),
    .D(data_in[7]),
    .DE(_081_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(\mem[0] [7]));
 sky130_fd_sc_hd__dfxtp_1 _365_ (.CLK(clknet_3_7__leaf_clk),
    .D(_090_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(rd_ptr[0]));
 sky130_fd_sc_hd__dfxtp_1 _366_ (.CLK(clknet_3_7__leaf_clk),
    .D(_095_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(rd_ptr[1]));
 sky130_fd_sc_hd__dfxtp_1 _367_ (.CLK(clknet_3_7__leaf_clk),
    .D(_094_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(rd_ptr[2]));
 sky130_fd_sc_hd__dfxtp_1 _368_ (.CLK(clknet_3_5__leaf_clk),
    .D(_096_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(rd_ptr[3]));
 sky130_fd_sc_hd__dfxtp_1 _369_ (.CLK(clknet_3_5__leaf_clk),
    .D(_093_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(wr_ptr[0]));
 sky130_fd_sc_hd__dfxtp_1 _370_ (.CLK(clknet_3_5__leaf_clk),
    .D(_092_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(wr_ptr[1]));
 sky130_fd_sc_hd__dfxtp_1 _371_ (.CLK(clknet_3_5__leaf_clk),
    .D(_091_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(wr_ptr[2]));
 sky130_fd_sc_hd__dfxtp_1 _372_ (.CLK(clknet_3_5__leaf_clk),
    .D(_097_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(wr_ptr[3]));
 sky130_fd_sc_hd__edfxtp_1 _373_ (.CLK(clknet_3_7__leaf_clk),
    .D(_073_),
    .DE(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(data_out[0]));
 sky130_fd_sc_hd__edfxtp_1 _374_ (.CLK(clknet_3_0__leaf_clk),
    .D(_074_),
    .DE(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(data_out[1]));
 sky130_fd_sc_hd__edfxtp_1 _375_ (.CLK(clknet_3_2__leaf_clk),
    .D(_075_),
    .DE(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(data_out[2]));
 sky130_fd_sc_hd__edfxtp_1 _376_ (.CLK(clknet_3_6__leaf_clk),
    .D(_076_),
    .DE(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(data_out[3]));
 sky130_fd_sc_hd__edfxtp_1 _377_ (.CLK(clknet_3_3__leaf_clk),
    .D(_077_),
    .DE(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(data_out[4]));
 sky130_fd_sc_hd__edfxtp_1 _378_ (.CLK(clknet_3_5__leaf_clk),
    .D(_078_),
    .DE(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(data_out[5]));
 sky130_fd_sc_hd__edfxtp_1 _379_ (.CLK(clknet_3_2__leaf_clk),
    .D(_079_),
    .DE(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(data_out[6]));
 sky130_fd_sc_hd__edfxtp_1 _380_ (.CLK(clknet_3_3__leaf_clk),
    .D(_080_),
    .DE(_089_),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .Q(data_out[7]));
 sky130_fd_sc_hd__clkbuf_4 clkbuf_0_clk (.A(clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(clknet_0_clk));
 sky130_fd_sc_hd__clkbuf_4 clkbuf_3_0__f_clk (.A(clknet_0_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(clknet_3_0__leaf_clk));
 sky130_fd_sc_hd__clkbuf_4 clkbuf_3_1__f_clk (.A(clknet_0_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(clknet_3_1__leaf_clk));
 sky130_fd_sc_hd__clkbuf_4 clkbuf_3_2__f_clk (.A(clknet_0_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(clknet_3_2__leaf_clk));
 sky130_fd_sc_hd__clkbuf_4 clkbuf_3_3__f_clk (.A(clknet_0_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(clknet_3_3__leaf_clk));
 sky130_fd_sc_hd__clkbuf_4 clkbuf_3_4__f_clk (.A(clknet_0_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(clknet_3_4__leaf_clk));
 sky130_fd_sc_hd__clkbuf_4 clkbuf_3_5__f_clk (.A(clknet_0_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(clknet_3_5__leaf_clk));
 sky130_fd_sc_hd__clkbuf_4 clkbuf_3_6__f_clk (.A(clknet_0_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(clknet_3_6__leaf_clk));
 sky130_fd_sc_hd__clkbuf_4 clkbuf_3_7__f_clk (.A(clknet_0_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD),
    .X(clknet_3_7__leaf_clk));
 sky130_fd_sc_hd__clkinv_2 clkload0 (.A(clknet_3_1__leaf_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD));
 sky130_fd_sc_hd__clkinv_1 clkload1 (.A(clknet_3_2__leaf_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD));
 sky130_fd_sc_hd__clkinv_2 clkload2 (.A(clknet_3_3__leaf_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD));
 sky130_fd_sc_hd__clkinv_4 clkload3 (.A(clknet_3_4__leaf_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD));
 sky130_fd_sc_hd__clkinvlp_4 clkload4 (.A(clknet_3_5__leaf_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD));
 sky130_fd_sc_hd__bufinv_16 clkload5 (.A(clknet_3_6__leaf_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD));
 sky130_fd_sc_hd__clkbuf_1 clkload6 (.A(clknet_3_7__leaf_clk),
    .VGND(VGND),
    .VNB(VGND),
    .VPB(VDD),
    .VPWR(VDD));
 assign empty = _098_;
 assign full = _099_;
 assign overflow = _205_;
 assign underflow = _212_;
endmodule
