/* Generated by Yosys 0.63+190 (git sha1 37ca545b6, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "syn_fifo.v:1.1-51.10" *)
module syn_fifo(rst, clk, wr_en, rd_en, data_in, full, empty, overflow, underflow, data_out);
  (* src = "syn_fifo.v:6.29-6.32" *)
  input rst;
  wire rst;
  (* src = "syn_fifo.v:7.29-7.32" *)
  input clk;
  wire clk;
  (* src = "syn_fifo.v:8.29-8.34" *)
  input wr_en;
  wire wr_en;
  (* src = "syn_fifo.v:9.29-9.34" *)
  input rd_en;
  wire rd_en;
  (* src = "syn_fifo.v:10.29-10.36" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "syn_fifo.v:11.29-11.33" *)
  output full;
  wire full;
  (* src = "syn_fifo.v:12.29-12.34" *)
  output empty;
  wire empty;
  (* src = "syn_fifo.v:13.29-13.37" *)
  output overflow;
  wire overflow;
  (* src = "syn_fifo.v:14.29-14.38" *)
  output underflow;
  wire underflow;
  (* src = "syn_fifo.v:15.29-15.37" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  (* src = "syn_fifo.v:36.23-36.48|/usr/local/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  (* src = "syn_fifo.v:12.29-12.34" *)
  wire _098_;
  (* src = "syn_fifo.v:11.29-11.33" *)
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  (* src = "syn_fifo.v:13.29-13.37" *)
  wire _205_;
  (* src = "syn_fifo.v:9.29-9.34" *)
  wire _206_;
  (* src = "syn_fifo.v:18.25-18.31" *)
  wire _207_;
  (* src = "syn_fifo.v:18.25-18.31" *)
  wire _208_;
  (* src = "syn_fifo.v:18.25-18.31" *)
  wire _209_;
  (* src = "syn_fifo.v:18.25-18.31" *)
  wire _210_;
  (* src = "syn_fifo.v:6.29-6.32" *)
  wire _211_;
  (* src = "syn_fifo.v:14.29-14.38" *)
  wire _212_;
  (* src = "syn_fifo.v:8.29-8.34" *)
  wire _213_;
  (* src = "syn_fifo.v:19.25-19.31" *)
  wire _214_;
  (* src = "syn_fifo.v:19.25-19.31" *)
  wire _215_;
  (* src = "syn_fifo.v:19.25-19.31" *)
  wire _216_;
  (* src = "syn_fifo.v:19.25-19.31" *)
  wire _217_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:37.23-37.47|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _218_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:37.23-37.47|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _219_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:36.23-36.48|/usr/local/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [3:0] _220_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:36.23-36.48|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _221_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:36.23-36.48|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  (* src = "syn_fifo.v:18.25-18.31" *)
  wire [3:0] rd_ptr;
  (* src = "syn_fifo.v:19.25-19.31" *)
  wire [3:0] wr_ptr;
  sky130_fd_sc_hd__clkinv_1 _231_ (
    .A(_206_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__clkinv_1 _232_ (
    .A(_213_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__mux4_2 _233_ (
    .A0(_114_),
    .A1(_146_),
    .A2(_130_),
    .A3(_162_),
    .S0(_209_),
    .S1(_208_),
    .X(_166_)
  );
  sky130_fd_sc_hd__mux4_2 _234_ (
    .A0(_106_),
    .A1(_138_),
    .A2(_122_),
    .A3(_154_),
    .S0(_209_),
    .S1(_208_),
    .X(_167_)
  );
  sky130_fd_sc_hd__mux2_1 _235_ (
    .A0(_167_),
    .A1(_166_),
    .S(_207_),
    .X(_079_)
  );
  sky130_fd_sc_hd__mux4_2 _236_ (
    .A0(_113_),
    .A1(_145_),
    .A2(_129_),
    .A3(_161_),
    .S0(_209_),
    .S1(_208_),
    .X(_168_)
  );
  sky130_fd_sc_hd__mux4_2 _237_ (
    .A0(_105_),
    .A1(_137_),
    .A2(_121_),
    .A3(_153_),
    .S0(_209_),
    .S1(_208_),
    .X(_169_)
  );
  sky130_fd_sc_hd__mux2_1 _238_ (
    .A0(_169_),
    .A1(_168_),
    .S(_207_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux4_2 _239_ (
    .A0(_112_),
    .A1(_144_),
    .A2(_128_),
    .A3(_160_),
    .S0(_209_),
    .S1(_208_),
    .X(_170_)
  );
  sky130_fd_sc_hd__mux4_2 _240_ (
    .A0(_104_),
    .A1(_136_),
    .A2(_120_),
    .A3(_152_),
    .S0(_209_),
    .S1(_208_),
    .X(_171_)
  );
  sky130_fd_sc_hd__mux2_1 _241_ (
    .A0(_171_),
    .A1(_170_),
    .S(_207_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux4_2 _242_ (
    .A0(_111_),
    .A1(_143_),
    .A2(_127_),
    .A3(_159_),
    .S0(_209_),
    .S1(_208_),
    .X(_172_)
  );
  sky130_fd_sc_hd__mux4_2 _243_ (
    .A0(_103_),
    .A1(_135_),
    .A2(_119_),
    .A3(_151_),
    .S0(_209_),
    .S1(_208_),
    .X(_173_)
  );
  sky130_fd_sc_hd__mux2_1 _244_ (
    .A0(_173_),
    .A1(_172_),
    .S(_207_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux4_2 _245_ (
    .A0(_110_),
    .A1(_142_),
    .A2(_126_),
    .A3(_158_),
    .S0(_209_),
    .S1(_208_),
    .X(_174_)
  );
  sky130_fd_sc_hd__mux4_2 _246_ (
    .A0(_102_),
    .A1(_134_),
    .A2(_118_),
    .A3(_150_),
    .S0(_209_),
    .S1(_208_),
    .X(_175_)
  );
  sky130_fd_sc_hd__mux2_1 _247_ (
    .A0(_175_),
    .A1(_174_),
    .S(_207_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux4_2 _248_ (
    .A0(_109_),
    .A1(_141_),
    .A2(_125_),
    .A3(_157_),
    .S0(_209_),
    .S1(_208_),
    .X(_176_)
  );
  sky130_fd_sc_hd__mux4_2 _249_ (
    .A0(_101_),
    .A1(_133_),
    .A2(_117_),
    .A3(_149_),
    .S0(_209_),
    .S1(_208_),
    .X(_177_)
  );
  sky130_fd_sc_hd__mux2_1 _250_ (
    .A0(_177_),
    .A1(_176_),
    .S(_207_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux4_2 _251_ (
    .A0(_108_),
    .A1(_140_),
    .A2(_124_),
    .A3(_156_),
    .S0(_209_),
    .S1(_208_),
    .X(_178_)
  );
  sky130_fd_sc_hd__mux4_2 _252_ (
    .A0(_100_),
    .A1(_132_),
    .A2(_116_),
    .A3(_148_),
    .S0(_209_),
    .S1(_208_),
    .X(_179_)
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(_179_),
    .A1(_178_),
    .S(_207_),
    .X(_073_)
  );
  sky130_fd_sc_hd__xnor2_1 _254_ (
    .A(_207_),
    .B(_214_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__xnor2_1 _255_ (
    .A(_209_),
    .B(_216_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__xnor2_1 _256_ (
    .A(_208_),
    .B(_215_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nand3_1 _257_ (
    .A(_180_),
    .B(_181_),
    .C(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__xor2_1 _258_ (
    .A(_217_),
    .B(_210_),
    .X(_184_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(_217_),
    .B(_210_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nor2_1 _260_ (
    .A(_183_),
    .B(_184_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a41oi_1 _261_ (
    .A1(_180_),
    .A2(_181_),
    .A3(_182_),
    .A4(_185_),
    .B1(_164_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand4_1 _262_ (
    .A(_180_),
    .B(_181_),
    .C(_182_),
    .D(_184_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__clkinv_1 _263_ (
    .A(_186_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a41oi_1 _264_ (
    .A1(_180_),
    .A2(_181_),
    .A3(_182_),
    .A4(_184_),
    .B1(_165_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(_213_),
    .B(_186_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__and2_0 _266_ (
    .A(_214_),
    .B(_187_),
    .X(_189_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(_215_),
    .B(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _268_ (
    .A(_216_),
    .B(_190_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2b_1 _269_ (
    .A_N(_215_),
    .B(_216_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nor3_1 _270_ (
    .A(_214_),
    .B(_188_),
    .C(_191_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor4b_1 _271_ (
    .A(_214_),
    .B(_188_),
    .C(_216_),
    .D_N(_215_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _272_ (
    .A(_189_),
    .SLEEP(_191_),
    .X(_086_)
  );
  sky130_fd_sc_hd__nor3b_1 _273_ (
    .A(_216_),
    .B(_215_),
    .C_N(_189_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor4_1 _274_ (
    .A(_214_),
    .B(_216_),
    .C(_215_),
    .D(_188_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__mux4_2 _275_ (
    .A0(_115_),
    .A1(_147_),
    .A2(_131_),
    .A3(_163_),
    .S0(_209_),
    .S1(_208_),
    .X(_192_)
  );
  sky130_fd_sc_hd__mux4_2 _276_ (
    .A0(_107_),
    .A1(_139_),
    .A2(_123_),
    .A3(_155_),
    .S0(_209_),
    .S1(_208_),
    .X(_193_)
  );
  sky130_fd_sc_hd__mux2_1 _277_ (
    .A0(_193_),
    .A1(_192_),
    .S(_207_),
    .X(_080_)
  );
  sky130_fd_sc_hd__and4b_1 _278_ (
    .A_N(_214_),
    .B(_216_),
    .C(_215_),
    .D(_187_),
    .X(_087_)
  );
  sky130_fd_sc_hd__and4_1 _279_ (
    .A(_214_),
    .B(_216_),
    .C(_215_),
    .D(_187_),
    .X(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _280_ (
    .A(_165_),
    .B(_186_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nor3_1 _281_ (
    .A(_164_),
    .B(_183_),
    .C(_184_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__and2_0 _282_ (
    .A(_207_),
    .B(_089_),
    .X(_194_)
  );
  sky130_fd_sc_hd__nor2_1 _283_ (
    .A(_207_),
    .B(_089_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nor3_1 _284_ (
    .A(_211_),
    .B(_194_),
    .C(_195_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a21oi_1 _285_ (
    .A1(_215_),
    .A2(_189_),
    .B1(_216_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nor3_1 _286_ (
    .A(_211_),
    .B(_088_),
    .C(_196_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _287_ (
    .A1(_215_),
    .A2(_189_),
    .B1(_211_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o21a_1 _288_ (
    .A1(_215_),
    .A2(_189_),
    .B1(_197_),
    .X(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _289_ (
    .A(_214_),
    .B(_187_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor3_1 _290_ (
    .A(_211_),
    .B(_189_),
    .C(_198_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__and3_1 _291_ (
    .A(_209_),
    .B(_208_),
    .C(_194_),
    .X(_199_)
  );
  sky130_fd_sc_hd__nand4_1 _292_ (
    .A(_209_),
    .B(_207_),
    .C(_208_),
    .D(_089_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__a21oi_1 _293_ (
    .A1(_208_),
    .A2(_194_),
    .B1(_209_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nor3_1 _294_ (
    .A(_211_),
    .B(_199_),
    .C(_201_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a21oi_1 _295_ (
    .A1(_208_),
    .A2(_194_),
    .B1(_211_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__o21a_1 _296_ (
    .A1(_208_),
    .A2(_194_),
    .B1(_202_),
    .X(_095_)
  );
  sky130_fd_sc_hd__xor2_1 _297_ (
    .A(_210_),
    .B(_200_),
    .X(_203_)
  );
  sky130_fd_sc_hd__nor2_1 _298_ (
    .A(_211_),
    .B(_203_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xnor2_1 _299_ (
    .A(_217_),
    .B(_088_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor2_1 _300_ (
    .A(_211_),
    .B(_204_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__edfxtp_1 _301_ (
    .CLK(clk),
    .D(data_in[0]),
    .DE(_008_),
    .Q(\mem[7] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _302_ (
    .CLK(clk),
    .D(data_in[1]),
    .DE(_008_),
    .Q(\mem[7] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _303_ (
    .CLK(clk),
    .D(data_in[2]),
    .DE(_008_),
    .Q(\mem[7] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _304_ (
    .CLK(clk),
    .D(data_in[3]),
    .DE(_008_),
    .Q(\mem[7] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _305_ (
    .CLK(clk),
    .D(data_in[4]),
    .DE(_008_),
    .Q(\mem[7] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _306_ (
    .CLK(clk),
    .D(data_in[5]),
    .DE(_008_),
    .Q(\mem[7] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _307_ (
    .CLK(clk),
    .D(data_in[6]),
    .DE(_008_),
    .Q(\mem[7] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _308_ (
    .CLK(clk),
    .D(data_in[7]),
    .DE(_008_),
    .Q(\mem[7] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _309_ (
    .CLK(clk),
    .D(data_in[0]),
    .DE(_007_),
    .Q(\mem[6] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _310_ (
    .CLK(clk),
    .D(data_in[1]),
    .DE(_007_),
    .Q(\mem[6] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _311_ (
    .CLK(clk),
    .D(data_in[2]),
    .DE(_007_),
    .Q(\mem[6] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _312_ (
    .CLK(clk),
    .D(data_in[3]),
    .DE(_007_),
    .Q(\mem[6] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _313_ (
    .CLK(clk),
    .D(data_in[4]),
    .DE(_007_),
    .Q(\mem[6] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _314_ (
    .CLK(clk),
    .D(data_in[5]),
    .DE(_007_),
    .Q(\mem[6] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _315_ (
    .CLK(clk),
    .D(data_in[6]),
    .DE(_007_),
    .Q(\mem[6] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _316_ (
    .CLK(clk),
    .D(data_in[7]),
    .DE(_007_),
    .Q(\mem[6] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _317_ (
    .CLK(clk),
    .D(data_in[0]),
    .DE(_006_),
    .Q(\mem[5] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _318_ (
    .CLK(clk),
    .D(data_in[1]),
    .DE(_006_),
    .Q(\mem[5] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _319_ (
    .CLK(clk),
    .D(data_in[2]),
    .DE(_006_),
    .Q(\mem[5] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _320_ (
    .CLK(clk),
    .D(data_in[3]),
    .DE(_006_),
    .Q(\mem[5] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _321_ (
    .CLK(clk),
    .D(data_in[4]),
    .DE(_006_),
    .Q(\mem[5] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _322_ (
    .CLK(clk),
    .D(data_in[5]),
    .DE(_006_),
    .Q(\mem[5] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _323_ (
    .CLK(clk),
    .D(data_in[6]),
    .DE(_006_),
    .Q(\mem[5] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _324_ (
    .CLK(clk),
    .D(data_in[7]),
    .DE(_006_),
    .Q(\mem[5] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _325_ (
    .CLK(clk),
    .D(data_in[0]),
    .DE(_005_),
    .Q(\mem[4] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _326_ (
    .CLK(clk),
    .D(data_in[1]),
    .DE(_005_),
    .Q(\mem[4] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _327_ (
    .CLK(clk),
    .D(data_in[2]),
    .DE(_005_),
    .Q(\mem[4] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _328_ (
    .CLK(clk),
    .D(data_in[3]),
    .DE(_005_),
    .Q(\mem[4] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _329_ (
    .CLK(clk),
    .D(data_in[4]),
    .DE(_005_),
    .Q(\mem[4] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _330_ (
    .CLK(clk),
    .D(data_in[5]),
    .DE(_005_),
    .Q(\mem[4] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _331_ (
    .CLK(clk),
    .D(data_in[6]),
    .DE(_005_),
    .Q(\mem[4] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _332_ (
    .CLK(clk),
    .D(data_in[7]),
    .DE(_005_),
    .Q(\mem[4] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _333_ (
    .CLK(clk),
    .D(data_in[0]),
    .DE(_004_),
    .Q(\mem[3] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _334_ (
    .CLK(clk),
    .D(data_in[1]),
    .DE(_004_),
    .Q(\mem[3] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _335_ (
    .CLK(clk),
    .D(data_in[2]),
    .DE(_004_),
    .Q(\mem[3] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _336_ (
    .CLK(clk),
    .D(data_in[3]),
    .DE(_004_),
    .Q(\mem[3] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _337_ (
    .CLK(clk),
    .D(data_in[4]),
    .DE(_004_),
    .Q(\mem[3] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _338_ (
    .CLK(clk),
    .D(data_in[5]),
    .DE(_004_),
    .Q(\mem[3] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _339_ (
    .CLK(clk),
    .D(data_in[6]),
    .DE(_004_),
    .Q(\mem[3] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _340_ (
    .CLK(clk),
    .D(data_in[7]),
    .DE(_004_),
    .Q(\mem[3] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _341_ (
    .CLK(clk),
    .D(data_in[0]),
    .DE(_003_),
    .Q(\mem[2] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _342_ (
    .CLK(clk),
    .D(data_in[1]),
    .DE(_003_),
    .Q(\mem[2] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _343_ (
    .CLK(clk),
    .D(data_in[2]),
    .DE(_003_),
    .Q(\mem[2] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _344_ (
    .CLK(clk),
    .D(data_in[3]),
    .DE(_003_),
    .Q(\mem[2] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _345_ (
    .CLK(clk),
    .D(data_in[4]),
    .DE(_003_),
    .Q(\mem[2] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _346_ (
    .CLK(clk),
    .D(data_in[5]),
    .DE(_003_),
    .Q(\mem[2] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _347_ (
    .CLK(clk),
    .D(data_in[6]),
    .DE(_003_),
    .Q(\mem[2] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _348_ (
    .CLK(clk),
    .D(data_in[7]),
    .DE(_003_),
    .Q(\mem[2] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _349_ (
    .CLK(clk),
    .D(data_in[0]),
    .DE(_002_),
    .Q(\mem[1] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _350_ (
    .CLK(clk),
    .D(data_in[1]),
    .DE(_002_),
    .Q(\mem[1] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _351_ (
    .CLK(clk),
    .D(data_in[2]),
    .DE(_002_),
    .Q(\mem[1] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _352_ (
    .CLK(clk),
    .D(data_in[3]),
    .DE(_002_),
    .Q(\mem[1] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _353_ (
    .CLK(clk),
    .D(data_in[4]),
    .DE(_002_),
    .Q(\mem[1] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _354_ (
    .CLK(clk),
    .D(data_in[5]),
    .DE(_002_),
    .Q(\mem[1] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _355_ (
    .CLK(clk),
    .D(data_in[6]),
    .DE(_002_),
    .Q(\mem[1] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _356_ (
    .CLK(clk),
    .D(data_in[7]),
    .DE(_002_),
    .Q(\mem[1] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _357_ (
    .CLK(clk),
    .D(data_in[0]),
    .DE(_001_),
    .Q(\mem[0] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _358_ (
    .CLK(clk),
    .D(data_in[1]),
    .DE(_001_),
    .Q(\mem[0] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _359_ (
    .CLK(clk),
    .D(data_in[2]),
    .DE(_001_),
    .Q(\mem[0] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _360_ (
    .CLK(clk),
    .D(data_in[3]),
    .DE(_001_),
    .Q(\mem[0] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _361_ (
    .CLK(clk),
    .D(data_in[4]),
    .DE(_001_),
    .Q(\mem[0] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _362_ (
    .CLK(clk),
    .D(data_in[5]),
    .DE(_001_),
    .Q(\mem[0] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _363_ (
    .CLK(clk),
    .D(data_in[6]),
    .DE(_001_),
    .Q(\mem[0] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _364_ (
    .CLK(clk),
    .D(data_in[7]),
    .DE(_001_),
    .Q(\mem[0] [7])
  );
  (* src = "syn_fifo.v:31.5-39.8" *)
  sky130_fd_sc_hd__dfxtp_1 _365_ (
    .CLK(clk),
    .D(_223_),
    .Q(rd_ptr[0])
  );
  (* src = "syn_fifo.v:31.5-39.8" *)
  sky130_fd_sc_hd__dfxtp_1 _366_ (
    .CLK(clk),
    .D(_228_),
    .Q(rd_ptr[1])
  );
  (* src = "syn_fifo.v:31.5-39.8" *)
  sky130_fd_sc_hd__dfxtp_1 _367_ (
    .CLK(clk),
    .D(_227_),
    .Q(rd_ptr[2])
  );
  (* src = "syn_fifo.v:31.5-39.8" *)
  sky130_fd_sc_hd__dfxtp_1 _368_ (
    .CLK(clk),
    .D(_229_),
    .Q(rd_ptr[3])
  );
  (* src = "syn_fifo.v:31.5-39.8" *)
  sky130_fd_sc_hd__dfxtp_1 _369_ (
    .CLK(clk),
    .D(_226_),
    .Q(wr_ptr[0])
  );
  (* src = "syn_fifo.v:31.5-39.8" *)
  sky130_fd_sc_hd__dfxtp_1 _370_ (
    .CLK(clk),
    .D(_225_),
    .Q(wr_ptr[1])
  );
  (* src = "syn_fifo.v:31.5-39.8" *)
  sky130_fd_sc_hd__dfxtp_1 _371_ (
    .CLK(clk),
    .D(_224_),
    .Q(wr_ptr[2])
  );
  (* src = "syn_fifo.v:31.5-39.8" *)
  sky130_fd_sc_hd__dfxtp_1 _372_ (
    .CLK(clk),
    .D(_230_),
    .Q(wr_ptr[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _373_ (
    .CLK(clk),
    .D(_000_[0]),
    .DE(_220_[0]),
    .Q(data_out[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _374_ (
    .CLK(clk),
    .D(_000_[1]),
    .DE(_220_[0]),
    .Q(data_out[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _375_ (
    .CLK(clk),
    .D(_000_[2]),
    .DE(_220_[0]),
    .Q(data_out[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _376_ (
    .CLK(clk),
    .D(_000_[3]),
    .DE(_220_[0]),
    .Q(data_out[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _377_ (
    .CLK(clk),
    .D(_000_[4]),
    .DE(_220_[0]),
    .Q(data_out[4])
  );
  sky130_fd_sc_hd__edfxtp_1 _378_ (
    .CLK(clk),
    .D(_000_[5]),
    .DE(_220_[0]),
    .Q(data_out[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _379_ (
    .CLK(clk),
    .D(_000_[6]),
    .DE(_220_[0]),
    .Q(data_out[6])
  );
  sky130_fd_sc_hd__edfxtp_1 _380_ (
    .CLK(clk),
    .D(_000_[7]),
    .DE(_220_[0]),
    .Q(data_out[7])
  );
  assign _220_[3:1] = 3'h0;
  assign _222_[0] = _221_[0];
  assign _218_[3:1] = wr_ptr[3:1];
  assign _219_[0] = _218_[0];
  assign _221_[3:1] = rd_ptr[3:1];
  assign _122_ = \mem[2] [6];
  assign _154_ = \mem[6] [6];
  assign _209_ = rd_ptr[2];
  assign _207_ = rd_ptr[0];
  assign _114_ = \mem[1] [6];
  assign _146_ = \mem[5] [6];
  assign _106_ = \mem[0] [6];
  assign _138_ = \mem[4] [6];
  assign _208_ = rd_ptr[1];
  assign _000_[6] = _079_;
  assign _129_ = \mem[3] [5];
  assign _161_ = \mem[7] [5];
  assign _121_ = \mem[2] [5];
  assign _153_ = \mem[6] [5];
  assign _113_ = \mem[1] [5];
  assign _145_ = \mem[5] [5];
  assign _105_ = \mem[0] [5];
  assign _137_ = \mem[4] [5];
  assign _000_[5] = _078_;
  assign _128_ = \mem[3] [4];
  assign _160_ = \mem[7] [4];
  assign _120_ = \mem[2] [4];
  assign _152_ = \mem[6] [4];
  assign _112_ = \mem[1] [4];
  assign _144_ = \mem[5] [4];
  assign _104_ = \mem[0] [4];
  assign _136_ = \mem[4] [4];
  assign _000_[4] = _077_;
  assign _127_ = \mem[3] [3];
  assign _159_ = \mem[7] [3];
  assign _119_ = \mem[2] [3];
  assign _151_ = \mem[6] [3];
  assign _111_ = \mem[1] [3];
  assign _143_ = \mem[5] [3];
  assign _103_ = \mem[0] [3];
  assign _135_ = \mem[4] [3];
  assign _000_[3] = _076_;
  assign _126_ = \mem[3] [2];
  assign _158_ = \mem[7] [2];
  assign _118_ = \mem[2] [2];
  assign _150_ = \mem[6] [2];
  assign _110_ = \mem[1] [2];
  assign _142_ = \mem[5] [2];
  assign _102_ = \mem[0] [2];
  assign _134_ = \mem[4] [2];
  assign _000_[2] = _075_;
  assign _125_ = \mem[3] [1];
  assign _157_ = \mem[7] [1];
  assign _117_ = \mem[2] [1];
  assign _149_ = \mem[6] [1];
  assign _109_ = \mem[1] [1];
  assign _141_ = \mem[5] [1];
  assign _101_ = \mem[0] [1];
  assign _133_ = \mem[4] [1];
  assign _000_[1] = _074_;
  assign _124_ = \mem[3] [0];
  assign _156_ = \mem[7] [0];
  assign _116_ = \mem[2] [0];
  assign _148_ = \mem[6] [0];
  assign _108_ = \mem[1] [0];
  assign _140_ = \mem[5] [0];
  assign _100_ = \mem[0] [0];
  assign _132_ = \mem[4] [0];
  assign _000_[0] = _073_;
  assign _214_ = wr_ptr[0];
  assign _216_ = wr_ptr[2];
  assign _215_ = wr_ptr[1];
  assign _217_ = wr_ptr[3];
  assign _210_ = rd_ptr[3];
  assign empty = _098_;
  assign _206_ = rd_en;
  assign _220_[0] = _089_;
  assign full = _099_;
  assign _213_ = wr_en;
  assign _004_ = _084_;
  assign _005_ = _085_;
  assign _003_ = _083_;
  assign _006_ = _086_;
  assign _002_ = _082_;
  assign _001_ = _081_;
  assign _131_ = \mem[3] [7];
  assign _163_ = \mem[7] [7];
  assign _123_ = \mem[2] [7];
  assign _155_ = \mem[6] [7];
  assign _115_ = \mem[1] [7];
  assign _147_ = \mem[5] [7];
  assign _107_ = \mem[0] [7];
  assign _139_ = \mem[4] [7];
  assign _000_[7] = _080_;
  assign _007_ = _087_;
  assign _008_ = _088_;
  assign overflow = _205_;
  assign underflow = _212_;
  assign _130_ = \mem[3] [6];
  assign _162_ = \mem[7] [6];
  assign _211_ = rst;
  assign _223_ = _090_;
  assign _224_ = _091_;
  assign _225_ = _092_;
  assign _226_ = _093_;
  assign _227_ = _094_;
  assign _228_ = _095_;
  assign _229_ = _096_;
  assign _230_ = _097_;
endmodule
