/* Generated by Yosys 0.63+190 (git sha1 37ca545b6, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "syn_fifo.v:1.1-51.10" *)
module syn_fifo(rst, clk, wr_en, rd_en, data_in, full, empty, overflow, underflow, data_out);
  (* src = "syn_fifo.v:6.29-6.32" *)
  input rst;
  wire rst;
  (* src = "syn_fifo.v:7.29-7.32" *)
  input clk;
  wire clk;
  (* src = "syn_fifo.v:8.29-8.34" *)
  input wr_en;
  wire wr_en;
  (* src = "syn_fifo.v:9.29-9.34" *)
  input rd_en;
  wire rd_en;
  (* src = "syn_fifo.v:10.29-10.36" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "syn_fifo.v:11.29-11.33" *)
  output full;
  wire full;
  (* src = "syn_fifo.v:12.29-12.34" *)
  output empty;
  wire empty;
  (* src = "syn_fifo.v:13.29-13.37" *)
  output overflow;
  wire overflow;
  (* src = "syn_fifo.v:14.29-14.38" *)
  output underflow;
  wire underflow;
  (* src = "syn_fifo.v:15.29-15.37" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:37.23-37.47|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _073_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:37.23-37.47|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _074_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:36.23-36.48|/usr/local/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [3:0] _075_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:36.23-36.48|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _076_;
  (* force_downto = 32'd1 *)
  (* src = "syn_fifo.v:36.23-36.48|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _077_;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  (* src = "syn_fifo.v:18.25-18.31" *)
  reg [3:0] rd_ptr;
  (* src = "syn_fifo.v:19.25-19.31" *)
  reg [3:0] wr_ptr;
  assign _009_ = rd_ptr[1] ? \mem[7] [6] : \mem[5] [6];
  assign _010_ = rd_ptr[1] ? \mem[3] [6] : \mem[1] [6];
  assign _011_ = rd_ptr[2] ? _009_ : _010_;
  assign _012_ = rd_ptr[1] ? \mem[6] [6] : \mem[4] [6];
  assign _013_ = rd_ptr[1] ? \mem[2] [6] : \mem[0] [6];
  assign _014_ = rd_ptr[2] ? _012_ : _013_;
  assign _000_[6] = rd_ptr[0] ? _011_ : _014_;
  assign _015_ = rd_ptr[1] ? \mem[7] [5] : \mem[5] [5];
  assign _016_ = rd_ptr[1] ? \mem[3] [5] : \mem[1] [5];
  assign _017_ = rd_ptr[2] ? _015_ : _016_;
  assign _018_ = rd_ptr[1] ? \mem[6] [5] : \mem[4] [5];
  assign _019_ = rd_ptr[1] ? \mem[2] [5] : \mem[0] [5];
  assign _020_ = rd_ptr[2] ? _018_ : _019_;
  assign _000_[5] = rd_ptr[0] ? _017_ : _020_;
  assign _021_ = rd_ptr[1] ? \mem[7] [4] : \mem[5] [4];
  assign _022_ = rd_ptr[1] ? \mem[3] [4] : \mem[1] [4];
  assign _023_ = rd_ptr[2] ? _021_ : _022_;
  assign _024_ = rd_ptr[1] ? \mem[6] [4] : \mem[4] [4];
  assign _025_ = rd_ptr[1] ? \mem[2] [4] : \mem[0] [4];
  assign _026_ = rd_ptr[2] ? _024_ : _025_;
  assign _000_[4] = rd_ptr[0] ? _023_ : _026_;
  assign _027_ = rd_ptr[1] ? \mem[7] [3] : \mem[5] [3];
  assign _028_ = rd_ptr[1] ? \mem[3] [3] : \mem[1] [3];
  assign _029_ = rd_ptr[2] ? _027_ : _028_;
  assign _030_ = rd_ptr[1] ? \mem[6] [3] : \mem[4] [3];
  assign _031_ = rd_ptr[1] ? \mem[2] [3] : \mem[0] [3];
  assign _032_ = rd_ptr[2] ? _030_ : _031_;
  assign _000_[3] = rd_ptr[0] ? _029_ : _032_;
  assign _033_ = rd_ptr[1] ? \mem[7] [2] : \mem[5] [2];
  assign _034_ = rd_ptr[1] ? \mem[3] [2] : \mem[1] [2];
  assign _035_ = rd_ptr[2] ? _033_ : _034_;
  assign _036_ = rd_ptr[1] ? \mem[6] [2] : \mem[4] [2];
  assign _037_ = rd_ptr[1] ? \mem[2] [2] : \mem[0] [2];
  assign _038_ = rd_ptr[2] ? _036_ : _037_;
  assign _000_[2] = rd_ptr[0] ? _035_ : _038_;
  assign _039_ = rd_ptr[1] ? \mem[7] [1] : \mem[5] [1];
  assign _040_ = rd_ptr[1] ? \mem[3] [1] : \mem[1] [1];
  assign _041_ = rd_ptr[2] ? _039_ : _040_;
  assign _042_ = rd_ptr[1] ? \mem[6] [1] : \mem[4] [1];
  assign _043_ = rd_ptr[1] ? \mem[2] [1] : \mem[0] [1];
  assign _044_ = rd_ptr[2] ? _042_ : _043_;
  assign _000_[1] = rd_ptr[0] ? _041_ : _044_;
  assign _045_ = rd_ptr[1] ? \mem[7] [0] : \mem[5] [0];
  assign _046_ = rd_ptr[1] ? \mem[3] [0] : \mem[1] [0];
  assign _047_ = rd_ptr[2] ? _045_ : _046_;
  assign _048_ = rd_ptr[1] ? \mem[6] [0] : \mem[4] [0];
  assign _049_ = rd_ptr[1] ? \mem[2] [0] : \mem[0] [0];
  assign _050_ = rd_ptr[2] ? _048_ : _049_;
  assign _000_[0] = rd_ptr[0] ? _047_ : _050_;
  assign _051_ = ~(rd_ptr[1] ^ wr_ptr[1]);
  assign _052_ = ~(rd_ptr[2] ^ wr_ptr[2]);
  assign _053_ = ~(rd_ptr[0] ^ wr_ptr[0]);
  assign _054_ = _052_ & _053_;
  assign _055_ = _051_ & _054_;
  assign _056_ = ~(wr_ptr[3] ^ rd_ptr[3]);
  assign empty = _055_ & _056_;
  assign _075_[0] = rd_en & ~(empty);
  assign _057_ = rd_ptr[0] & _075_[0];
  assign _058_ = rd_ptr[1] & _057_;
  assign _059_ = ~(rd_ptr[2] & _058_);
  assign _077_[3] = ~(rd_ptr[3] ^ _059_);
  assign _077_[2] = rd_ptr[2] ^ _058_;
  assign full = _055_ & ~(_056_);
  assign _060_ = wr_en & ~(full);
  assign _061_ = wr_ptr[0] & _060_;
  assign _062_ = wr_ptr[1] & _061_;
  assign _074_[1] = wr_ptr[1] ^ _061_;
  assign _063_ = _060_ & ~(wr_ptr[0]);
  assign _073_[0] = wr_ptr[0] ^ _060_;
  assign _004_ = _062_ & ~(wr_ptr[2]);
  assign _074_[2] = wr_ptr[2] ^ _062_;
  assign _076_[0] = rd_ptr[0] ^ _075_[0];
  assign _064_ = wr_ptr[2] & ~(wr_ptr[1]);
  assign _006_ = _061_ & _064_;
  assign _065_ = wr_ptr[1] & _063_;
  assign _003_ = _065_ & ~(wr_ptr[2]);
  assign _066_ = ~(wr_ptr[1] | wr_ptr[2]);
  assign _002_ = _061_ & _066_;
  assign _005_ = _063_ & _064_;
  assign _001_ = _063_ & _066_;
  assign _067_ = rd_ptr[1] ? \mem[7] [7] : \mem[5] [7];
  assign _068_ = rd_ptr[1] ? \mem[3] [7] : \mem[1] [7];
  assign _069_ = rd_ptr[2] ? _067_ : _068_;
  assign _070_ = rd_ptr[1] ? \mem[6] [7] : \mem[4] [7];
  assign _071_ = rd_ptr[1] ? \mem[2] [7] : \mem[0] [7];
  assign _072_ = rd_ptr[2] ? _070_ : _071_;
  assign _000_[7] = rd_ptr[0] ? _069_ : _072_;
  assign _007_ = wr_ptr[2] & _065_;
  assign _008_ = wr_ptr[2] & _062_;
  assign _074_[3] = wr_ptr[3] ^ _008_;
  assign overflow = wr_en & full;
  assign underflow = rd_en & empty;
  assign _077_[1] = rd_ptr[1] ^ _057_;
  always @(posedge clk)
    if (_008_) \mem[7] [0] <= data_in[0];
  always @(posedge clk)
    if (_008_) \mem[7] [1] <= data_in[1];
  always @(posedge clk)
    if (_008_) \mem[7] [2] <= data_in[2];
  always @(posedge clk)
    if (_008_) \mem[7] [3] <= data_in[3];
  always @(posedge clk)
    if (_008_) \mem[7] [4] <= data_in[4];
  always @(posedge clk)
    if (_008_) \mem[7] [5] <= data_in[5];
  always @(posedge clk)
    if (_008_) \mem[7] [6] <= data_in[6];
  always @(posedge clk)
    if (_008_) \mem[7] [7] <= data_in[7];
  always @(posedge clk)
    if (_007_) \mem[6] [0] <= data_in[0];
  always @(posedge clk)
    if (_007_) \mem[6] [1] <= data_in[1];
  always @(posedge clk)
    if (_007_) \mem[6] [2] <= data_in[2];
  always @(posedge clk)
    if (_007_) \mem[6] [3] <= data_in[3];
  always @(posedge clk)
    if (_007_) \mem[6] [4] <= data_in[4];
  always @(posedge clk)
    if (_007_) \mem[6] [5] <= data_in[5];
  always @(posedge clk)
    if (_007_) \mem[6] [6] <= data_in[6];
  always @(posedge clk)
    if (_007_) \mem[6] [7] <= data_in[7];
  always @(posedge clk)
    if (_006_) \mem[5] [0] <= data_in[0];
  always @(posedge clk)
    if (_006_) \mem[5] [1] <= data_in[1];
  always @(posedge clk)
    if (_006_) \mem[5] [2] <= data_in[2];
  always @(posedge clk)
    if (_006_) \mem[5] [3] <= data_in[3];
  always @(posedge clk)
    if (_006_) \mem[5] [4] <= data_in[4];
  always @(posedge clk)
    if (_006_) \mem[5] [5] <= data_in[5];
  always @(posedge clk)
    if (_006_) \mem[5] [6] <= data_in[6];
  always @(posedge clk)
    if (_006_) \mem[5] [7] <= data_in[7];
  always @(posedge clk)
    if (_005_) \mem[4] [0] <= data_in[0];
  always @(posedge clk)
    if (_005_) \mem[4] [1] <= data_in[1];
  always @(posedge clk)
    if (_005_) \mem[4] [2] <= data_in[2];
  always @(posedge clk)
    if (_005_) \mem[4] [3] <= data_in[3];
  always @(posedge clk)
    if (_005_) \mem[4] [4] <= data_in[4];
  always @(posedge clk)
    if (_005_) \mem[4] [5] <= data_in[5];
  always @(posedge clk)
    if (_005_) \mem[4] [6] <= data_in[6];
  always @(posedge clk)
    if (_005_) \mem[4] [7] <= data_in[7];
  always @(posedge clk)
    if (_004_) \mem[3] [0] <= data_in[0];
  always @(posedge clk)
    if (_004_) \mem[3] [1] <= data_in[1];
  always @(posedge clk)
    if (_004_) \mem[3] [2] <= data_in[2];
  always @(posedge clk)
    if (_004_) \mem[3] [3] <= data_in[3];
  always @(posedge clk)
    if (_004_) \mem[3] [4] <= data_in[4];
  always @(posedge clk)
    if (_004_) \mem[3] [5] <= data_in[5];
  always @(posedge clk)
    if (_004_) \mem[3] [6] <= data_in[6];
  always @(posedge clk)
    if (_004_) \mem[3] [7] <= data_in[7];
  always @(posedge clk)
    if (_003_) \mem[2] [0] <= data_in[0];
  always @(posedge clk)
    if (_003_) \mem[2] [1] <= data_in[1];
  always @(posedge clk)
    if (_003_) \mem[2] [2] <= data_in[2];
  always @(posedge clk)
    if (_003_) \mem[2] [3] <= data_in[3];
  always @(posedge clk)
    if (_003_) \mem[2] [4] <= data_in[4];
  always @(posedge clk)
    if (_003_) \mem[2] [5] <= data_in[5];
  always @(posedge clk)
    if (_003_) \mem[2] [6] <= data_in[6];
  always @(posedge clk)
    if (_003_) \mem[2] [7] <= data_in[7];
  always @(posedge clk)
    if (_002_) \mem[1] [0] <= data_in[0];
  always @(posedge clk)
    if (_002_) \mem[1] [1] <= data_in[1];
  always @(posedge clk)
    if (_002_) \mem[1] [2] <= data_in[2];
  always @(posedge clk)
    if (_002_) \mem[1] [3] <= data_in[3];
  always @(posedge clk)
    if (_002_) \mem[1] [4] <= data_in[4];
  always @(posedge clk)
    if (_002_) \mem[1] [5] <= data_in[5];
  always @(posedge clk)
    if (_002_) \mem[1] [6] <= data_in[6];
  always @(posedge clk)
    if (_002_) \mem[1] [7] <= data_in[7];
  always @(posedge clk)
    if (_001_) \mem[0] [0] <= data_in[0];
  always @(posedge clk)
    if (_001_) \mem[0] [1] <= data_in[1];
  always @(posedge clk)
    if (_001_) \mem[0] [2] <= data_in[2];
  always @(posedge clk)
    if (_001_) \mem[0] [3] <= data_in[3];
  always @(posedge clk)
    if (_001_) \mem[0] [4] <= data_in[4];
  always @(posedge clk)
    if (_001_) \mem[0] [5] <= data_in[5];
  always @(posedge clk)
    if (_001_) \mem[0] [6] <= data_in[6];
  always @(posedge clk)
    if (_001_) \mem[0] [7] <= data_in[7];
  (* src = "syn_fifo.v:31.5-39.8" *)
  always @(posedge clk)
    if (rst) wr_ptr[0] <= 1'h0;
    else wr_ptr[0] <= _073_[0];
  (* src = "syn_fifo.v:31.5-39.8" *)
  always @(posedge clk)
    if (rst) wr_ptr[1] <= 1'h0;
    else wr_ptr[1] <= _074_[1];
  (* src = "syn_fifo.v:31.5-39.8" *)
  always @(posedge clk)
    if (rst) wr_ptr[2] <= 1'h0;
    else wr_ptr[2] <= _074_[2];
  (* src = "syn_fifo.v:31.5-39.8" *)
  always @(posedge clk)
    if (rst) wr_ptr[3] <= 1'h0;
    else wr_ptr[3] <= _074_[3];
  (* src = "syn_fifo.v:31.5-39.8" *)
  always @(posedge clk)
    if (rst) rd_ptr[0] <= 1'h0;
    else rd_ptr[0] <= _076_[0];
  (* src = "syn_fifo.v:31.5-39.8" *)
  always @(posedge clk)
    if (rst) rd_ptr[1] <= 1'h0;
    else rd_ptr[1] <= _077_[1];
  (* src = "syn_fifo.v:31.5-39.8" *)
  always @(posedge clk)
    if (rst) rd_ptr[2] <= 1'h0;
    else rd_ptr[2] <= _077_[2];
  (* src = "syn_fifo.v:31.5-39.8" *)
  always @(posedge clk)
    if (rst) rd_ptr[3] <= 1'h0;
    else rd_ptr[3] <= _077_[3];
  always @(posedge clk)
    if (_075_[0]) data_out[0] <= _000_[0];
  always @(posedge clk)
    if (_075_[0]) data_out[1] <= _000_[1];
  always @(posedge clk)
    if (_075_[0]) data_out[2] <= _000_[2];
  always @(posedge clk)
    if (_075_[0]) data_out[3] <= _000_[3];
  always @(posedge clk)
    if (_075_[0]) data_out[4] <= _000_[4];
  always @(posedge clk)
    if (_075_[0]) data_out[5] <= _000_[5];
  always @(posedge clk)
    if (_075_[0]) data_out[6] <= _000_[6];
  always @(posedge clk)
    if (_075_[0]) data_out[7] <= _000_[7];
  assign _075_[3:1] = 3'h0;
  assign _077_[0] = _076_[0];
  assign _073_[3:1] = wr_ptr[3:1];
  assign _074_[0] = _073_[0];
  assign _076_[3:1] = rd_ptr[3:1];
endmodule
